// Content for the Bogeybeasts landing page.
// Beast names, types + rarities lifted from the app first_gen_bogeybeasts data.

export const steps = [
  {
    n: '01',
    title: 'Start a round',
    body: 'Pick from 217 real courses across Sweden — or add your own. Play 9 or 18 holes.',
  },
  {
    n: '02',
    title: 'Play each hole',
    body: 'Log your score: eagle, birdie, par, bogey, and everything beyond.',
  },
  {
    n: '03',
    title: 'Encounter a Bogeybeast',
    body: 'On each hole a Bogeybeast appears on the course, weighted by rarity tier.',
  },
  {
    n: '04',
    title: 'Make the catch',
    body: 'Your golf score drives the catch rate. Play well, catch more — Legendaries won’t come easy.',
  },
];

export const rarities = [
  { tier: 'Common', weight: '35%', par: '100%', color: '#9CB89C' },
  { tier: 'Uncommon', weight: '25%', par: '95%', color: '#26A69A' },
  { tier: 'Rare', weight: '20%', par: '90%', color: '#4FC3F7' },
  { tier: 'Epic', weight: '14%', par: '70%', color: '#C792EA' },
  { tier: 'Legendary', weight: '6%', par: '40%', color: '#FFD700' },
];

export const rarityColor = {
  Common: '#9CB89C',
  Uncommon: '#26A69A',
  Rare: '#4FC3F7',
  Epic: '#C792EA',
  Legendary: '#FFD700',
};

// All 151 first-gen Bogeybeasts.
export const allBeasts = [
  { id: "001", name: "Puttling", type: "Grass", rarity: "Uncommon" },
  { id: "002", name: "Fairwyn", type: "Grass", rarity: "Rare" },
  { id: "003", name: "Teelord", type: "Grass · Poison", rarity: "Epic" },
  { id: "004", name: "Bogferno", type: "Fire", rarity: "Uncommon" },
  { id: "005", name: "Parablaze", type: "Fire", rarity: "Rare" },
  { id: "006", name: "Emberdie", type: "Fire · Flying", rarity: "Epic" },
  { id: "007", name: "Droptooth", type: "Water", rarity: "Uncommon" },
  { id: "008", name: "Bladogator", type: "Water", rarity: "Rare" },
  { id: "009", name: "Hookodile", type: "Water", rarity: "Epic" },
  { id: "010", name: "Roughrat", type: "Grass", rarity: "Common" },
  { id: "011", name: "Growdent", type: "Grass", rarity: "Uncommon" },
  { id: "012", name: "Crisprdi", type: "Flying · Ice", rarity: "Common" },
  { id: "013", name: "Chilleagle", type: "Flying · Ice", rarity: "Uncommon" },
  { id: "014", name: "Albafrosst", type: "Flying · Ice", rarity: "Epic" },
  { id: "015", name: "Babydraw", type: "Normal", rarity: "Common" },
  { id: "016", name: "Snaphook", type: "Normal", rarity: "Uncommon" },
  { id: "017", name: "Tinyfade", type: "Normal", rarity: "Common" },
  { id: "018", name: "Bautaslice", type: "Normal", rarity: "Uncommon" },
  { id: "019", name: "Tappin", type: "Normal", rarity: "Uncommon" },
  { id: "020", name: "Stimpee", type: "Normal", rarity: "Uncommon" },
  { id: "021", name: "Missuno", type: "Bug", rarity: "Common" },
  { id: "022", name: "Adidos", type: "Bug", rarity: "Uncommon" },
  { id: "023", name: "Titliestres", type: "Bug · Poison", rarity: "Rare" },
  { id: "024", name: "Owtofbouns", type: "Poison · Flying", rarity: "Common" },
  { id: "025", name: "Strekathol", type: "Poison · Flying", rarity: "Rare" },
  { id: "026", name: "Tristlie", type: "Ground", rarity: "Uncommon" },
  { id: "027", name: "Horchunk", type: "Ground", rarity: "Rare" },
  { id: "028", name: "Stenfan", type: "Rock", rarity: "Uncommon" },
  { id: "029", name: "Sabakloba", type: "Rock", rarity: "Rare" },
  { id: "030", name: "Bongker", type: "Ground", rarity: "Uncommon" },
  { id: "031", name: "Naynayron", type: "Rock", rarity: "Common" },
  { id: "032", name: "Sevenayron", type: "Rock", rarity: "Uncommon" },
  { id: "033", name: "Fayvayron", type: "Rock", rarity: "Rare" },
  { id: "034", name: "Splish", type: "Water", rarity: "Common" },
  { id: "035", name: "Plooms", type: "Water · Ice", rarity: "Rare" },
  { id: "036", name: "Pinnhai", type: "Water · Grass", rarity: "Uncommon" },
  { id: "037", name: "Komindo", type: "Water", rarity: "Common" },
  { id: "038", name: "Denharvi", type: "Water · Electric", rarity: "Uncommon" },
  { id: "039", name: "Laypup", type: "Fire", rarity: "Uncommon" },
  { id: "040", name: "Stingler", type: "Water · Poison", rarity: "Common" },
  { id: "041", name: "Stungyard", type: "Water · Poison", rarity: "Rare" },
  { id: "042", name: "Bugbag", type: "Bug · Poison", rarity: "Common" },
  { id: "043", name: "Acicart", type: "Bug · Poison", rarity: "Uncommon" },
  { id: "044", name: "Toxicaddie", type: "Bug · Poison", rarity: "Rare" },
  { id: "045", name: "Bogistragl", type: "Ice", rarity: "Uncommon" },
  { id: "046", name: "Bawrapawr", type: "Ice", rarity: "Rare" },
  { id: "047", name: "Lipowlt", type: "Fire · Flying", rarity: "Common" },
  { id: "048", name: "Lagphoot", type: "Fire · Flying", rarity: "Uncommon" },
  { id: "049", name: "Rongclub", type: "Electric · Ground", rarity: "Uncommon" },
  { id: "050", name: "Hotstreek", type: "Electric · Fire", rarity: "Uncommon" },
  { id: "051", name: "Holeoblaze", type: "Electric · Fire", rarity: "Rare" },
  { id: "052", name: "Zapwedge", type: "Electric", rarity: "Common" },
  { id: "053", name: "Greeninreg", type: "Electric", rarity: "Uncommon" },
  { id: "054", name: "Skaiad", type: "Electric · Flying", rarity: "Common" },
  { id: "055", name: "Skaimarx", type: "Electric · Flying", rarity: "Uncommon" },
  { id: "056", name: "Secondcat", type: "Grass · Dark", rarity: "Common" },
  { id: "057", name: "Frincheetah", type: "Grass · Dark", rarity: "Uncommon" },
  { id: "058", name: "Tigerwudz", type: "Grass · Dark", rarity: "Rare" },
  { id: "059", name: "Spinbite", type: "Dark", rarity: "Uncommon" },
  { id: "060", name: "Kortosne", type: "Dragon", rarity: "Common" },
  { id: "061", name: "Longorak", type: "Dragon", rarity: "Uncommon" },
  { id: "062", name: "Seet", type: "Ice", rarity: "Common" },
  { id: "063", name: "Menstanado", type: "Ice · Flying", rarity: "Uncommon" },
  { id: "064", name: "Elektrindor", type: "Electric", rarity: "Common" },
  { id: "065", name: "Voltrakman", type: "Electric", rarity: "Uncommon" },
  { id: "066", name: "Undulathon", type: "Flying", rarity: "Uncommon" },
  { id: "067", name: "Zepestance", type: "Ground", rarity: "Uncommon" },
  { id: "068", name: "Rovtchip", type: "Grass · Ground", rarity: "Rare" },
  { id: "069", name: "Shankey", type: "Fighting · Ice", rarity: "Common" },
  { id: "070", name: "Socketfeil", type: "Fighting · Ice", rarity: "Uncommon" },
  { id: "071", name: "Dumduff", type: "Ground", rarity: "Uncommon" },
  { id: "072", name: "Deevot", type: "Ground", rarity: "Common" },
  { id: "073", name: "OBwan", type: "Psychic", rarity: "Common" },
  { id: "074", name: "Proveewan", type: "Psychic", rarity: "Uncommon" },
  { id: "075", name: "Holinwangenobi", type: "Psychic · Dragon", rarity: "Epic" },
  { id: "076", name: "Peboll", type: "Water", rarity: "Uncommon" },
  { id: "077", name: "Profesorfisk", type: "Water", rarity: "Common" },
  { id: "078", name: "Lawnshangle", type: "Grass · Fighting", rarity: "Common" },
  { id: "079", name: "Spinrayt", type: "Grass · Fighting", rarity: "Uncommon" },
  { id: "080", name: "Smashfakdurr", type: "Grass · Fighting", rarity: "Epic" },
  { id: "081", name: "Jinx", type: "Psychic", rarity: "Rare" },
  { id: "082", name: "Skobra", type: "Ghost · Poison", rarity: "Common" },
  { id: "083", name: "Skrixon", type: "Ghost · Poison", rarity: "Uncommon" },
  { id: "084", name: "Skullaway", type: "Ghost · Poison", rarity: "Epic" },
  { id: "085", name: "Rangewhelp", type: "Dragon", rarity: "Common" },
  { id: "086", name: "Yardrake", type: "Dragon", rarity: "Uncommon" },
  { id: "087", name: "Carryhazard", type: "Dragon", rarity: "Epic" },
  { id: "088", name: "Ofdedeck", type: "Grass · Ground", rarity: "Common" },
  { id: "089", name: "Pangdrayv", type: "Grass · Ground", rarity: "Uncommon" },
  { id: "090", name: "Drayvagreen", type: "Ground · Dragon", rarity: "Epic" },
  { id: "091", name: "Teetaim", type: "Bug · Fighting", rarity: "Common" },
  { id: "092", name: "Penaltee", type: "Bug · Fighting", rarity: "Uncommon" },
  { id: "093", name: "Teeboxer", type: "Bug · Fighting", rarity: "Rare" },
  { id: "094", name: "Chipin", type: "Flying", rarity: "Common" },
  { id: "095", name: "Flopshot", type: "Flying · Rock", rarity: "Uncommon" },
  { id: "096", name: "Clarva", type: "Rock · Psychic", rarity: "Common" },
  { id: "097", name: "Denneclar", type: "Rock · Psychic", rarity: "Rare" },
  { id: "098", name: "Gripslip", type: "Ice · Normal", rarity: "Uncommon" },
  { id: "099", name: "Skrambell", type: "Fire · Water", rarity: "Rare" },
  { id: "100", name: "Alsquare", type: "Psychic", rarity: "Uncommon" },
  { id: "101", name: "Doormee", type: "Psychic", rarity: "Rare" },
  { id: "102", name: "Jossi", type: "Psychic", rarity: "Uncommon" },
  { id: "103", name: "Suooja", type: "Psychic · Flying", rarity: "Rare" },
  { id: "104", name: "Chipamboo", type: "Ghost", rarity: "Common" },
  { id: "105", name: "Bumpandarun", type: "Ghost", rarity: "Uncommon" },
  { id: "106", name: "Upandawn", type: "Ghost · Dark", rarity: "Epic" },
  { id: "107", name: "Grinfee", type: "Dark · Poison", rarity: "Uncommon" },
  { id: "108", name: "Bladagast", type: "Psychic · Grass", rarity: "Common" },
  { id: "109", name: "Mulligandalf", type: "Psychic · Grass", rarity: "Uncommon" },
  { id: "110", name: "Strekstrek", type: "Flying", rarity: "Common" },
  { id: "111", name: "Bogibardi", type: "Flying", rarity: "Uncommon" },
  { id: "112", name: "Ritebreak", type: "Ghost · Fighting", rarity: "Rare" },
  { id: "113", name: "Linkskors", type: "Ground", rarity: "Uncommon" },
  { id: "114", name: "Thindit", type: "Rock", rarity: "Common" },
  { id: "115", name: "Fuooor", type: "Rock", rarity: "Rare" },
  { id: "116", name: "Fringeputt", type: "Fire · Psychic", rarity: "Common" },
  { id: "117", name: "Indahowl", type: "Fire · Psychic", rarity: "Rare" },
  { id: "118", name: "Plugfuk", type: "Bug · Ground", rarity: "Uncommon" },
  { id: "119", name: "Legdog", type: "Grass · Fighting", rarity: "Uncommon" },
  { id: "120", name: "Trigglett", type: "Dark", rarity: "Common" },
  { id: "121", name: "Gigatilt", type: "Dark", rarity: "Rare" },
  { id: "122", name: "Fairwhayle", type: "Water", rarity: "Rare" },
  { id: "123", name: "Schneschlug", type: "Poison", rarity: "Uncommon" },
  { id: "124", name: "Eelonmask", type: "Electric · Poison", rarity: "Rare" },
  { id: "125", name: "Flatpitch", type: "Normal", rarity: "Uncommon" },
  { id: "126", name: "Pyrepitch", type: "Fire", rarity: "Epic" },
  { id: "127", name: "Tidepitch", type: "Water", rarity: "Epic" },
  { id: "128", name: "Elepitch", type: "Electric", rarity: "Epic" },
  { id: "129", name: "Grovepitch", type: "Grass", rarity: "Epic" },
  { id: "130", name: "Wintergreenor", type: "Ice · Grass", rarity: "Rare" },
  { id: "131", name: "Waggler", type: "Ghost", rarity: "Common" },
  { id: "132", name: "Proofswing", type: "Ghost · Fighting", rarity: "Rare" },
  { id: "133", name: "Sandstroke", type: "Ground", rarity: "Uncommon" },
  { id: "134", name: "Fahndoh", type: "Electric", rarity: "Uncommon" },
  { id: "135", name: "Yewlachit", type: "Electric", rarity: "Rare" },
  { id: "136", name: "Owberg", type: "Psychic · Ice", rarity: "Epic" },
  { id: "137", name: "Roary", type: "Dragon · Rock", rarity: "Epic" },
  { id: "138", name: "Shefflor", type: "Water · Psychic", rarity: "Epic" },
  { id: "139", name: "Braizon", type: "Fire · Dark", rarity: "Epic" },
  { id: "140", name: "Hee-Oh", type: "Fire · Bug", rarity: "Epic" },
  { id: "141", name: "Shee-Oh", type: "Electric · Bug", rarity: "Epic" },
  { id: "142", name: "Bogeyman", type: "Ghost", rarity: "Rare" },
  { id: "143", name: "Saintandrose", type: "Grass · Flying", rarity: "Epic" },
  { id: "144", name: "Frontanine", type: "Dark", rarity: "Rare" },
  { id: "145", name: "Bakanine", type: "Dark", rarity: "Epic" },
  { id: "146", name: "Touritslag", type: "Normal", rarity: "Rare" },
  { id: "147", name: "Yuessowpen", type: "Dragon · Flying", rarity: "Legendary" },
  { id: "148", name: "Deeowpen", type: "Dark · Flying", rarity: "Legendary" },
  { id: "149", name: "Pegeaychamp", type: "Dragon · Dark", rarity: "Legendary" },
  { id: "150", name: "Agustamastr", type: "Dragon · Electric", rarity: "Legendary" },
  { id: "151", name: "Kuondor", type: "Flying", rarity: "Legendary" },
];

// A curated dozen for the homepage teaser.
const showcaseIds = ['001', '004', '007', '025', '039', '052', '094', '130', '143', '149', '150', '151'];
export const beasts = allBeasts.filter((b) => showcaseIds.includes(b.id));
